// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "your-region",
    "aws_cognito_identity_pool_id": "your-identity-pool-id",
    "aws_cognito_region": "your-region",
    "aws_user_pools_id": "your-user-pool-id",
    "aws_user_pools_web_client_id": "your-app-client-id",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://your-api-url.appsync-api.your-region.amazonaws.com/graphql",
    "aws_appsync_region": "your-region",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "your-api-key-if-using-api-key-auth",
    "aws_user_files_s3_bucket": "your-s3-bucket-name",
    "aws_user_files_s3_bucket_region": "your-region",
    // other service configurations if needed
};

export default awsmobile;
